# Generated by Django 4.0.1 on 2022-01-18 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(default=models.CharField(max_length=100), max_length=100)),
                ('eamil', models.EmailField(max_length=100)),
                ('salary', models.FloatField(max_length=50)),
                ('details', models.TextField(max_length=100)),
                ('availabe', models.BooleanField()),
                ('catagory', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
